name: Deploy to Debo

on:
  push:
    branches: [ main ]  # 當 main 分支有推送時觸發
  workflow_dispatch:    # 允許手動觸發

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to Debo
      env:
        DEBO_TOKEN: ddp_McDZ7KMHteGsJJIDfGDFTJxRQQHLQR3mKGe4
      run: |
        # 安裝 Debo CLI（假設存在）
        npm install -g debo-cli
        
        # 登錄 Debo
        debo login --token $DEBO_TOKEN
        
        # 部署
        debo deploy